// getMovies.js
export const movies = {
  page: 1,
  total_pages: 1,
  total_results: 10,
  results: [
    {
      adult: false,
      backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: "en",
      original_title: "Spider-Man: No Way Home",
      overview: "Peter Parker navigates his senior year of high school while facing new villains from across the Multiverse.",
      popularity: 9876.543,
      poster_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      release_date: "2021-12-15",
      title: "Spider-Man: No Way Home",
      video: false,
      vote_average: 8.4,
      vote_count: 12500
    },
    {
      adult: false,
      backdrop_path: "/tcheoA2nPATCm2vvXw2hVQoaEFD.jpg",
      genre_ids: [12, 28, 14],
      id: 284053,
      original_language: "en",
      original_title: "Thor: Ragnarok",
      overview: "Thor must escape the alien planet Sakaar in time to save Asgard from Hela and the impending Ragnarök.",
      popularity: 8234.120,
      poster_path: "/tcheoA2nPATCm2vvXw2hVQoaEFD.jpg",
      release_date: "2017-10-25",
      title: "Thor: Ragnarok",
      video: false,
      vote_average: 7.9,
      vote_count: 10200
    },
    {
      adult: false,
      backdrop_path: "/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
      genre_ids: [28, 12, 878],
      id: 299536,
      original_language: "en",
      original_title: "Avengers: Infinity War",
      overview: "The Avengers must stop Thanos before he collects all six Infinity Stones and ends the universe.",
      popularity: 8800.45,
      poster_path: "/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
      release_date: "2018-04-27",
      title: "Avengers: Infinity War",
      video: false,
      vote_average: 8.5,
      vote_count: 24000
    },
    {
      adult: false,
      backdrop_path: "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
      genre_ids: [12, 28, 878],
      id: 299537,
      original_language: "en",
      original_title: "Avengers: Endgame",
      overview: "After the devastating events of Infinity War, the Avengers assemble once more to undo Thanos' actions.",
      popularity: 9100.72,
      poster_path: "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
      release_date: "2019-04-26",
      title: "Avengers: Endgame",
      video: false,
      vote_average: 8.4,
      vote_count: 26000
    },
    {
      adult: false,
      backdrop_path: "/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
      genre_ids: [18, 53, 9648],
      id: 11324,
      original_language: "en",
      original_title: "Gone Girl",
      overview: "With his wife’s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him.",
      popularity: 4500.78,
      poster_path: "/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
      release_date: "2014-10-03",
      title: "Gone Girl",
      video: false,
      vote_average: 8.1,
      vote_count: 14000
    },
    {
      adult: false,
      backdrop_path: "/cCTJPelKGLhALq3r51A9uMonxKj.jpg",
      genre_ids: [28, 53, 80],
      id: 603692,
      original_language: "en",
      original_title: "John Wick: Chapter 4",
      overview: "John Wick takes on his most lethal adversaries yet as he uncovers a path to defeating The High Table.",
      popularity: 8500.52,
      poster_path: "/cCTJPelKGLhALq3r51A9uMonxKj.jpg",
      release_date: "2023-03-24",
      title: "John Wick: Chapter 4",
      video: false,
      vote_average: 8.7,
      vote_count: 19500
    },
    
    {
      adult: false,
      backdrop_path: "/6ELJEzQJ3Y45HczvreC3dg0GV5R.jpg",
      genre_ids: [28, 12, 878],
      id: 497698,
      original_language: "en",
      original_title: "Black Widow",
      overview: "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy arises.",
      popularity: 6100.12,
      poster_path: "/6ELJEzQJ3Y45HczvreC3dg0GV5R.jpg",
      release_date: "2021-07-09",
      title: "Black Widow",
      video: false,
      vote_average: 6.8,
      vote_count: 9100
    },
    {
      adult: false,
      backdrop_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      popularity: 7000.65,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-07",
      title: "Interstellar",
      video: false,
      vote_average: 8.6,
      vote_count: 29000
    },
    {
      adult: false,
      backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: "en",
      original_title: "Forrest Gump",
      overview: "The story of Forrest Gump, a man with a low IQ who inadvertently influences many historical events.",
      popularity: 6700.25,
      poster_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
      release_date: "1994-07-06",
      title: "Forrest Gump",
      video: false,
      vote_average: 8.8,
      vote_count: 23000
    },
    {
      adult: false,
      backdrop_path: "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
      genre_ids: [28, 12, 14],
      id: 76341,
      original_language: "en",
      original_title: "Mad Max: Fury Road",
      overview: "In a post-apocalyptic wasteland, Max teams up with Furiosa to flee from a cult leader and his army.",
      popularity: 4900.33,
      poster_path: "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
      release_date: "2015-05-15",
      title: "Mad Max: Fury Road",
      video: false,
      vote_average: 8.1,
      vote_count: 21000
    }
  ]
};
